export const browserCoreExamples = [
  "prowl browser status",
  "prowl browser start",
  "prowl browser stop",
  "prowl browser tabs",
  "prowl browser open https://example.com",
  "prowl browser focus abcd1234",
  "prowl browser close abcd1234",
  "prowl browser screenshot",
  "prowl browser screenshot --full-page",
  "prowl browser screenshot --ref 12",
  "prowl browser snapshot",
  "prowl browser snapshot --format aria --limit 200",
  "prowl browser snapshot --efficient",
  "prowl browser snapshot --labels",
];

export const browserActionExamples = [
  "prowl browser navigate https://example.com",
  "prowl browser resize 1280 720",
  "prowl browser click 12 --double",
  'prowl browser type 23 "hello" --submit',
  "prowl browser press Enter",
  "prowl browser hover 44",
  "prowl browser drag 10 11",
  "prowl browser select 9 OptionA OptionB",
  "prowl browser upload /tmp/prowl/uploads/file.pdf",
  'prowl browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "prowl browser dialog --accept",
  'prowl browser wait --text "Done"',
  "prowl browser evaluate --fn '(el) => el.textContent' --ref 7",
  "prowl browser console --level error",
  "prowl browser pdf",
];
